two_d_mode: true
map_frame: map
odom_frame: odom
base_link_frame: herb_base
# Since the StarGazer provides global absolute position data, we should set
# world_frame to the same value as map_frame. The Segway driver is resposnible
# for publishing the odom to herb_base transform.
world_frame: map
# Segway RMP odometry. We ignore the Pose component of the message and only
# integrate twists.
odom0: segway_rmp_node/odom
odom0_config: [ false, false, false,  # x, y, z
                false, false, false,  # roll, pitch, yaw
                 true, false, false,  # x dot, y dot, z dot
                false, false,  true,  # roll dot, pitch dot, yaw dot
                false, false, false ] # x ddot, y ddot, z ddot
odom0_differential: false
# Stargazer readings. This specifies a full 6-DOF pose, but will be snapped
# into the plane by the "two_d_mode" flag.
pose0: robot_pose
pose0_config: [  true,  true, true,   # x, y, z
                 true,  true, true,   # roll, pitch, yaw
                false, false, false,  # x dot, y dot, z dot
                false, false, false,  # roll dot, pitch dot, yaw dot
                false, false, false ] # x ddot, y ddot, z ddot
pose0_differential: false
