bhd:
  # "high strain gauge" limit
  hsg_value: 10000
owd:
  cpus_to_run_on: 6,7
  canbus_number: 1
  modified_j1: true
  forcetorque_sensor: true
  # NOTE: hand_type must be a string, not an integer. Otherwise, OWD will
  # detect that no wrist is installed. This is potentially dangerous because
  # the inverse dynamics solution will be wildly incorrect.
  hand_type: '280'
  synchronization_id: 0
  motor1_transmission_ratio: 42.279465399975486
  motor2_transmission_ratio: 28.57420843798113
  motor3_transmission_ratio: 28.47704175190698
  motor4_transmission_ratio: 18.5773462763004
  motor5_transmission_ratio: 8.652577050573187
  motor6_transmission_ratio: 9.680541457118569
  motor7_transmission_ratio: 14.928346369504156
tf_prefix: right
