bhd:
  # "high strain gauge" limit
  hsg_value: 10000
owd:
  cpus_to_run_on: 6,7
  canbus_number: 1
  modified_j1: true
  forcetorque_sensor: true
  # NOTE: hand_type must be a string, not an integer. Otherwise, OWD will
  # detect that no wrist is installed. This is potentially dangerous because
  # the inverse dynamics solution will be wildly incorrect.
  hand_type: '280'
  # Temporarily disable s ynchronization because the left WAM is not installed
  # and the pantilt unit has not been ported to Catkin.
  synchronize_with_other_controllers: false
  synchronization_id: 0
tf_prefix: right
